apiVersion: v1
kind: Service
metadata:
  name: newsapp-service
  labels:
    app: newsapp
spec:
  type: LoadBalancer
  selector:
    app: newsapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  #sessionAffinity: None